-- Supabase Migration Schema for MoneyView Portfolio (v2)
-- Run this in the Supabase SQL Editor to add portfolio tables

CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT DEFAULT 'OTHER', -- 'CASH', 'STOCK', 'PENSION', 'CRYPTO', 'OTHER'
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS holdings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
  ticker TEXT NOT NULL,
  name TEXT NOT NULL,
  strategy TEXT,
  quantity NUMERIC NOT NULL DEFAULT 0,
  unit_price NUMERIC NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast holding lookup by account
CREATE INDEX IF NOT EXISTS idx_holdings_account_id ON holdings(account_id);

CREATE TABLE IF NOT EXISTS monthly_valuations (
  month TEXT NOT NULL, -- YYYY-MM
  account_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
  deposit BIGINT DEFAULT 0,
  valuation BIGINT DEFAULT 0,
  profit BIGINT DEFAULT 0,
  profit_rate NUMERIC DEFAULT 0,
  cumulative_profit BIGINT DEFAULT 0,
  twr NUMERIC DEFAULT 0,
  ytd NUMERIC DEFAULT 0,
  note TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (month, account_id)
);

-- Index for fast lookup by month
CREATE INDEX IF NOT EXISTS idx_monthly_valuations_month ON monthly_valuations(month);
