-- Supabase Migration Schema for MoneyView
-- Run this in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  note TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL,          -- YYYY-MM-DD
  content TEXT,                -- 지출내용
  amount BIGINT NOT NULL,      -- 지출금액
  category TEXT,               -- 소비분류
  type TEXT NOT NULL,          -- 'INCOME' | 'EXPENSE'
  merchant TEXT,               -- 매출처
  "orderNo" TEXT,              -- 주문번호
  "paymentMethod" TEXT,        -- 결제수단
  "businessNum" TEXT,          -- 사업자(번호)
  note TEXT,                   -- 비고
  status TEXT DEFAULT 'CONFIRMED', -- 'DRAFT' | 'CONFIRMED'
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(status);

CREATE TABLE IF NOT EXISTS monthly_stats (
  month TEXT PRIMARY KEY,        -- YYYY-MM
  real_estate BIGINT DEFAULT 0,  -- 부동산 (Manual input)
  liability_expr TEXT,           -- 부채 계산식 (Manual input string)
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);
